rvm:
  - 1.9.3

before_script: ./spec/ci/before_script

script: ./spec/ci/script

env:
  - RADIANT_VERSION=1.1.0 DB=mysql
  - RADIANT_VERSION=1.1.0 DB=postgres
  - RADIANT_VERSION=master DB=mysql
  - RADIANT_VERSION=master DB=postgres

notifications:
  recipients:
    - sam@samwhited.com
